import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Toaster } from "react-hot-toast";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Astrix Digital Media",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${montserrat.variable} antialiased`}>
        {/* <video
        className="absolute top-0 left-0 w-full h-full object-cover overflow-auto "
        src= "hero_vid.mp4"
        autoPlay
        loop
        muted
      /> */}
        <Toaster
          toastOptions={{
            position: "top-center",
            style: {
              borderRadius: "10px",
              background: "#333",
              color: "#fff",
            },
          }}
        />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
